spring:
  config:
    activate:
      on-profile: prod

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${rds.url}
    username: ${rds.username}
    password: ${rds.password}

  jackson:
    serialization:
      fail-on-empty-beans: false